import type { Metadata } from "next";
import Nav from "@/components/landing-page/Nav";
import Footer from "@/components/landing-page/Footer";
import { Providers } from "./providers";
import "../../styles/users.css";

export const metadata: Metadata = {
  title: "Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="text-foreground bg-background">
      <Providers>
        <Nav />
        {children}
        <Footer />
      </Providers>
    </div>
  );
}
