import type { Metadata } from "next";
import "@/styles/globals.css";
import { fontInter } from "@/libs/fonts/fonts";
import { Providers } from "@/components/Providers/Providers";

export const metadata: Metadata = {
  title: "English Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${fontInter.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
